"""empty message

Revision ID: 63c0057171af
Revises: 77fc8cf6bd8b
Create Date: 2023-11-22 21:03:40.930205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63c0057171af"
down_revision = "77fc8cf6bd8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("currencies", schema=None) as batch_op:
        batch_op.drop_constraint("currencies_code_key", type_="unique")
        batch_op.drop_column("code")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("currencies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("code", sa.VARCHAR(length=3), autoincrement=False, nullable=True)
        )
        batch_op.create_unique_constraint("currencies_code_key", ["code"])

    # ### end Alembic commands ###
