"""empty message

Revision ID: 77fc8cf6bd8b
Revises: e67a7018a6ab
Create Date: 2023-11-22 20:31:51.765585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77fc8cf6bd8b"
down_revision = "e67a7018a6ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("currency_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "currencies", ["currency_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("currency_id")

    # ### end Alembic commands ###
